name: rtd311
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandoc>=3.1,<4.0
  - nbsphinx
  - jupyter
  - matplotlib
  - sphinx=7.2.4
  - sphinx-copybutton
  - numpy
  - scipy==1.10.1
  - jax==0.4.13
  - jaxlib
  - diffmah==0.4.3
  - diffstar==0.2.2
  - dsps==0.3.6
  - h5py
  - healpy
  - mpi4py